version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/application_stop/stop_application.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/before_install/install_dependencies.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/before_install/install_mongodb.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install/install_packages.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application_start/deploy.sh
      timeout: 60
      runas: ubuntu
