MAXIMUM_COVERLETTER_NUMBER = 5

MAX_COMPANY_NAME_LENGTH = 15
MAX_POSITION_NAME_LENGTH = 30
MAX_RECRUITMENT_LENGTH = 1000
MAX_COVERLETTER_QUESTION_LENGTH = 100
MAX_COVERLETTER_ANSWER_LENGTH = 1500

MAX_KEYWORD_LENGTH = 30